spring:
  application:
    name: SocialMediaAPI
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
environment:
  R2_ACCESS_KEY: ${R2_ACCESS_KEY}
  R2_SECRET_KEY: ${R2_SECRET_KEY}
  R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
  R2_BUCKET_NAME: ${R2_BUCKET_NAME}
  PROD_URL: ${PROD_URL}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
  refresh:
    secret: ${JWT_REFRESH_SECRET}


